[versions]
accompanistMarkdown = "0.5.6"
accompanistPermissions = "0.37.3"
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activityCompose = "1.9.3"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.0"
androidx-core-ktx = "1.17.0"
androidx-espresso-core = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-material = "1.13.0"
androidx-test-junit = "1.3.0"
componentsResources = "1.10.0"
compose-multiplatform = "1.10.0"
coreSplashscreen = "1.2.0"
foundation = "1.10.0"
grantCore = "1.0.1"
graphicsShapes = "1.1.0"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinGradlePlugin = "1.9.0"
kotlinxCoroutinesCore = "1.10.2"
landscapistCoil3 = "2.9.3"
material = "1.10.0"
material3 = "1.11.0-alpha02"
materialIconsExtended = "1.7.3"
multiplatformMarkdownRendererM3 = "0.39.2"
napier = "2.7.1"
permissions = "0.20.1"
playServicesLocation = "21.3.0"
resourcesGenerator = "0.26.0"
graphics = "0.10.1"
datetime = "0.7.1"
coreI18n = "1.0.0"
ktor-client = "3.4.0"
buildKonfig = "0.17.1"
koin = "4.1.1"
koinComposeMultiplatform = "4.1.1"
navigationCompose = "2.9.7"
lifecycleViewModel = "2.10.0"
kotlinxSerializationJson = "1.10.0"
datastore = "1.2.0"
decompose = "3.4.0"
essenty = "2.5.0"
richeditorCompose = "1.0.0-rc13"
runtime = "1.10.0"
skie = "0.10.9"
aboutlibrariesCore = "14.0.0-b02"
firebaseCrashlytics = "20.0.4"
googleGmsGoogleServices = "4.4.4"
googleFirebaseCrashlytics = "3.0.3"
uiToolingPreview = "1.10.0"


[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "graphicsShapes" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
grant-core = { module = "dev.brewkits:grant-core", version.ref = "grantCore" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapistCoil3" }
material = { module = "org.jetbrains.compose.material:material", version.ref = "material" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatformMarkdownRendererM3" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissions" }
permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "permissions" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
resources = { module = "dev.icerock.moko:resources", version.ref = "resourcesGenerator" }
resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "resourcesGenerator" }
graphics = { module = "dev.icerock.moko:graphics", version.ref = "graphics" }
resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "resourcesGenerator" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime"}
androidx-core-i18n = { group = "androidx.core", name = "core-i18n", version.ref = "coreI18n" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor-client" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor-client" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-client" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-client" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-client" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-client" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeMultiplatform" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewModel"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-jetbrains-experiment = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }

essenty-stateKeeper = { group = "com.arkivanov.essenty", name = "state-keeper", version.ref = "essenty" }
essenty-instanceKeeper = { group = "com.arkivanov.essenty", name = "instance-keeper", version.ref = "essenty" }
essenty-backHandler = { group = "com.arkivanov.essenty", name = "back-handler", version.ref = "essenty" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibrariesCore" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibrariesCore" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiToolingPreview" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKMP = {id = "com.android.kotlin.multiplatform.library", version.ref = "agp"}
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
multiplatformResources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "resourcesGenerator"}
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
skie = {id = "co.touchlab.skie", version.ref = "skie"}
mikepenz-aboutlibrary = {id = "com.mikepenz.aboutlibraries.plugin",version.ref = "aboutlibrariesCore"}
mikepenz-aboutlibrary-android = {id = "com.mikepenz.aboutlibraries.plugin.android",version.ref = "aboutlibrariesCore"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

